import { Page } from "../types";
import { MODULE_COLORS } from "./ui";

export type ModuleStatus = "ACTIVE" | "PARTIAL" | "PENDING";

export interface BlueprintModule {
  id: string;
  pageId?: Page;
  title: string;
  status: ModuleStatus;
  iconKey: string;
  features: string[];
  colorKey: keyof typeof MODULE_COLORS;
  links?: { label: string; url: string; icon?: string }[];
}

export const BLUEPRINT_MODULES: BlueprintModule[] = [
  {
    id: "tasks",
    pageId: "MISSIONS",
    title: "Mission Control",
    status: "ACTIVE",
    iconKey: "Missions",
    features: [
      "Tactical mission execution",
      "Dependencies & blockers",
      "Milestones & priorities",
      "High-velocity output tracking",
    ],
    colorKey: "tasks",
    links: [
      { label: "Missions Sheet", url: "#", icon: "Database" },
      { label: "Execution SOP", url: "#", icon: "Docs" },
    ],
  },
  {
    id: "focus",
    pageId: "FOCUS",
    title: "The Deep Zone",
    status: "ACTIVE",
    iconKey: "Focus",
    features: [
      "Isolated execution environment",
      "Biometric state logging",
      "Cognitive load management",
      "Focus session analytics",
    ],
    colorKey: "tasks",
    links: [{ label: "Focus Protocol", url: "#", icon: "Target" }],
  },
  {
    id: "crm",
    pageId: "CRM",
    title: "CRM & Contact Layer",
    status: "ACTIVE",
    iconKey: "Users",
    features: [
      "Contacts / Clients / Vendors",
      "Interaction logs & history",
      "Follow-up reminders",
      "Task-linked networking",
    ],
    colorKey: "crm",
    links: [
      { label: "Contact Registry", url: "#", icon: "Users" },
      { label: "Networking SOP", url: "#", icon: "Docs" },
    ],
  },
  {
    id: "docs",
    pageId: "KNOWLEDGE",
    title: "Documentation & Intel",
    status: "ACTIVE",
    iconKey: "Docs",
    features: [
      "Markdown notes & SOPs",
      "Rich text formatting",
      "Searchable knowledge base",
      "Tag-based organization",
    ],
    colorKey: "docs",
    links: [
      { label: "Intel Repository", url: "#", icon: "Folder" },
      { label: "Markdown Guide", url: "#", icon: "Edit" },
    ],
  },
  {
    id: "analytics",
    pageId: "INSIGHTS",
    title: "Analytics & Insights",
    status: "ACTIVE",
    iconKey: "Analytics",
    features: [
      "Operational velocity charts",
      "Project completion stats",
      "Artifact unlock tracking",
      "Recharts: bars & radar",
    ],
    colorKey: "analytics",
    links: [{ label: "Velocity Report", url: "#", icon: "TrendUp" }],
  },
  {
    id: "automation",
    pageId: "AUTOMATION",
    title: "Automation Layer",
    status: "ACTIVE",
    iconKey: "Active",
    features: [
      "Event-driven triggers",
      "Smart agentic workflows",
      "Batch status updates",
      "GAS background syncing",
    ],
    colorKey: "automation",
    links: [
      { label: "GAS Console", url: "#", icon: "Terminal" },
      { label: "Webhook Setup", url: "#", icon: "Link" },
    ],
  },
  {
    id: "vault",
    pageId: "VAULT",
    title: "Secure Vault",
    status: "ACTIVE",
    iconKey: "Vault",
    features: [
      "AES-256 encrypted storage",
      "API tokens & secret keys",
      "One-click copy to clip",
      "Local data sovereignty",
    ],
    colorKey: "vault",
    links: [{ label: "Security Policy", url: "#", icon: "Lock" }],
  },
  {
    id: "ai",
    pageId: "WESAI",
    title: "AI Co-Pilot (WesAI)",
    status: "ACTIVE",
    iconKey: "Bot",
    features: [
      "Gemini 3 Flash Powered",
      "Context-aware execution",
      "Create/Update tasks",
      "Conversational strategy",
    ],
    colorKey: "ai",
    links: [
      { label: "Gemini AI Docs", url: "https://ai.google.dev/", icon: "Bot" },
      { label: "Prompt Library", url: "#", icon: "Chat" },
    ],
  },
  {
    id: "sovereign",
    pageId: "DASHBOARD",
    title: "Sovereign Command",
    status: "ACTIVE",
    iconKey: "Dashboard",
    features: [
      "Tactical Command Interface",
      "Operator XP & Leveling",
      "Real-time streak tracking",
      "Full Data Sovereignty",
    ],
    colorKey: "sovereign",
    links: [{ label: "Operator Manual", url: "#", icon: "Book" }],
  },
  {
    id: "strategy",
    pageId: "STRATEGY",
    title: "The Decision Layer",
    status: "ACTIVE",
    iconKey: "Strategy",
    features: [
      "Decision journal & accuracy",
      "Assumption tracking",
      "Strategy vs Tactic separation",
      "Outcome/Impact correlation",
    ],
    colorKey: "strategy",
    links: [
      { label: "Decision Journal", url: "#", icon: "Edit" },
      { label: "Strategic Framework", url: "#", icon: "Target" },
    ],
  },
  {
    id: "awareness",
    pageId: "AWARENESS",
    title: "Cognition & State",
    status: "ACTIVE",
    iconKey: "Activity",
    features: [
      "Energy & clarity tracking",
      "Mental state correlation",
      "Daily check-in rituals",
      "WesAI state coaching",
    ],
    colorKey: "awareness",
    links: [{ label: "State Tracking", url: "#", icon: "Activity" }],
  },
  {
    id: "assets",
    pageId: "ASSETS",
    title: "Asset & IP Registry",
    status: "ACTIVE",
    iconKey: "Project",
    features: [
      "SOP & Framework library",
      "Monetization potential score",
      "Code snippet vault",
      "External resource links",
    ],
    colorKey: "assets",
    links: [
      { label: "IP Inventory", url: "#", icon: "Database" },
      { label: "Asset SOP", url: "#", icon: "Docs" },
    ],
  },
  {
    id: "reflection",
    pageId: "REFLECTION",
    title: "Feedback & Reflection",
    status: "ACTIVE",
    iconKey: "History",
    features: [
      "Post-mortem close-outs",
      "Enforced reflection loops",
      "Mistake avoidance logs",
      "Systemization triggers",
    ],
    colorKey: "reflection",
    links: [{ label: "Reflection Logs", url: "#", icon: "History" }],
  },
  {
    id: "life",
    pageId: "LIFE",
    title: "Life Ops & Constraints",
    status: "ACTIVE",
    iconKey: "Heart",
    features: [
      "Health & recovery blocks",
      "Personal goal tracking",
      "Family commitments",
      "Energy-based scheduling",
    ],
    colorKey: "life",
    links: [{ label: "Life Protocol", url: "#", icon: "Heart" }],
  },
  {
    id: "integrations",
    pageId: "INTEGRATIONS",
    title: "Integration Hub",
    status: "ACTIVE",
    iconKey: "Link",
    features: [
      "Slack / WhatsApp / Email hooks",
      "Event-driven triggers",
      "One-click connection testing",
      "Automatic client sync",
    ],
    colorKey: "integrations",
    links: [{ label: "Hook Registry", url: "#", icon: "Link" }],
  },
  {
    id: "report",
    pageId: "REPORT",
    title: "Code Intelligence",
    status: "ACTIVE",
    iconKey: "Report",
    features: [
      "Automated health scans",
      "Architecture reporting",
      "Markdown report export",
      "Intelligence insights",
    ],
    colorKey: "report",
    links: [{ label: "Report History", url: "#", icon: "Report" }],
  },
  {
    id: "blueprint",
    pageId: "BLUEPRINT",
    title: "Master Blueprint",
    status: "ACTIVE",
    iconKey: "Blueprint",
    features: [
      "Solo Operator Roadmap",
      "Module status tracking",
      "Feature-set inventory",
      "Markdown blueprint export",
    ],
    colorKey: "strategy",
    links: [{ label: "Product Roadmap", url: "#", icon: "Map" }],
  },
  {
    id: "story",
    pageId: "STORY",
    title: "The Integration Story",
    status: "ACTIVE",
    iconKey: "History",
    features: [
      "Visual workflow mapping",
      "End-to-end data flow",
      "Action-to-Output story",
      "Sync hub visualization",
    ],
    colorKey: "integrations",
    links: [{ label: "Workflow Story", url: "#", icon: "History" }],
  },
  {
    id: "settings",
    pageId: "SETTINGS",
    title: "System Protocols",
    status: "ACTIVE",
    iconKey: "Settings",
    features: [
      "Core configuration layer",
      "Theme & UI optimization",
      "Data maintenance tools",
      "Access & security control",
    ],
    colorKey: "vault",
    links: [{ label: "System Config", url: "#", icon: "Settings" }],
  },
];
