import React, { useState } from "react";
import { Icon, iconProps } from "../Icons";
import { BLUEPRINT_MODULES } from "@/constants";
import { ViewHeader } from "../ViewHeader";

export const BlueprintView: React.FC = () => {
  const [copied, setCopied] = useState(false);

  const copyAsMarkdown = () => {
    const md = [
      "# Master Blueprint - Solo Operator Command Center Roadmap",
      "",
      ...BLUEPRINT_MODULES.map((mod) => {
        return [
          `## ${mod.title} [${mod.status}]`,
          ...mod.features.map((f) => `- ${f}`),
          "",
        ].join("\n");
      }),
      "---",
      "Generated by MyOps - Solo Operator Command Center",
    ].join("\n");

    navigator.clipboard.writeText(md).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <ViewHeader
        title="Master Blueprint"
        subTitle="Solo Operator Command Center Roadmap"
      >
        <button
          onClick={copyAsMarkdown}
          className="flex items-center gap-2 px-3 py-1.5 bg-notion-light-bg dark:bg-notion-dark-bg hover:bg-notion-light-sidebar dark:hover:bg-notion-dark-sidebar rounded-lg border border-notion-light-border dark:border-notion-dark-border text-[10px] font-bold text-notion-light-text dark:text-notion-dark-text transition-all group"
          title="Copy Roadmap as Markdown"
        >
          {copied ? (
            <Icon.Check size={14} className="text-emerald-500" />
          ) : (
            <Icon.Copy
              size={14}
              className="opacity-60 group-hover:opacity-100"
            />
          )}
          <span className="uppercase tracking-widest">
            {copied ? "Copied!" : "COPY"}
          </span>
        </button>

        <div className="flex items-center gap-2 px-3 py-1.5 bg-notion-light-sidebar dark:bg-notion-dark-sidebar rounded-lg border border-notion-light-border dark:border-notion-dark-border">
          <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)] animate-pulse"></div>
          <span className="text-[10px] font-bold text-notion-light-text dark:text-notion-dark-text opacity-70 uppercase tracking-widest">
            System v2.2 - Deployment Ready
          </span>
        </div>
      </ViewHeader>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {BLUEPRINT_MODULES.map((mod) => (
          <div
            key={mod.id}
            className="relative group bg-notion-light-bg dark:bg-notion-dark-bg border border-notion-light-border dark:border-notion-dark-border rounded-2xl p-6 hover:shadow-xl hover:border-notion-light-text/10 dark:hover:border-notion-dark-text/10 transition-all duration-300 overflow-hidden flex flex-col h-full"
          >
            <div
              className={`absolute top-0 right-0 w-32 h-32 bg-${mod.color}-500/5 dark:bg-${mod.color}-400/5 rounded-full -mr-16 -mt-16 group-hover:scale-150 transition-transform duration-700`}
            ></div>

            <div className="flex items-start justify-between mb-5 relative">
              <div
                className={`w-12 h-12 rounded-xl flex items-center justify-center bg-${mod.color}-100/50 dark:bg-${mod.color}-900/20 text-${mod.color}-600 dark:text-${mod.color}-400 border border-${mod.color}-200/50 dark:border-${mod.color}-800/30 transition-transform group-hover:scale-110 duration-300`}
              >
                {Icon[mod.iconKey as keyof typeof Icon] ? (
                  React.createElement(Icon[mod.iconKey as keyof typeof Icon], {
                    ...iconProps(24),
                  })
                ) : (
                  <Icon.Missions {...iconProps(24)} />
                )}
              </div>
              <span
                className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider shadow-sm ${
                  mod.status === "ACTIVE"
                    ? "bg-emerald-500/10 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-400 border border-emerald-500/20 dark:border-emerald-500/30"
                    : mod.status === "PARTIAL"
                      ? "bg-amber-500/10 text-amber-700 dark:bg-amber-500/20 dark:text-amber-400 border border-amber-500/20 dark:border-amber-500/30"
                      : "bg-notion-light-sidebar text-notion-light-muted dark:bg-notion-dark-sidebar dark:text-notion-dark-muted border border-notion-light-border dark:border-notion-dark-border"
                }`}
              >
                {mod.status}
              </span>
            </div>

            <h3 className="text-base font-bold text-notion-light-text dark:text-notion-dark-text mb-4 relative group-hover:text-notion-light-text/80 dark:group-hover:text-notion-dark-text/80 transition-colors">
              {mod.title}
            </h3>

            <ul className="space-y-3 relative flex-grow">
              {mod.features.map((f, i) => (
                <li
                  key={i}
                  className="flex items-start gap-2.5 text-[12px] text-notion-light-muted dark:text-notion-dark-muted group/item"
                >
                  <div
                    className={`mt-1.5 w-1.5 h-1.5 rounded-full bg-${mod.color}-400 opacity-60 group-hover/item:scale-125 transition-transform`}
                  ></div>
                  <span className="leading-tight">{f}</span>
                </li>
              ))}
            </ul>

            <div className="mt-8 pt-5 border-t border-notion-light-border dark:border-notion-dark-border flex items-center justify-between group-hover:border-notion-light-text/10 dark:group-hover:border-notion-dark-text/10 transition-colors">
              <button className="notion-button notion-button-ghost text-[10px] uppercase tracking-widest group-hover:translate-x-1">
                Initialize{" "}
                <Icon.Next
                  size={14}
                  className="opacity-0 group-hover:opacity-100 transition-opacity"
                />
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-notion-light-sidebar dark:bg-notion-dark-sidebar rounded-2xl p-8 border border-notion-light-border dark:border-notion-dark-border relative overflow-hidden group shadow-sm hover:shadow-md transition-all">
        <div className="absolute top-0 left-0 w-full h-1 bg-notion-light-text dark:bg-notion-dark-text opacity-20 group-hover:opacity-40 transition-opacity"></div>
        <div className="relative z-10 flex flex-col md:flex-row gap-8 items-start">
          <div className="flex-1">
            <h2 className="text-xl font-bold text-notion-light-text dark:text-notion-dark-text mb-4 flex items-center gap-3">
              <Icon.Bot
                size={24}
                className="text-notion-light-text dark:text-notion-dark-text opacity-70"
              />
              Operator Philosophy
            </h2>
            <p className="text-notion-light-muted dark:text-notion-dark-muted max-w-2xl leading-relaxed text-[15px]">
              The Master Solo VA App is more than a tool; it's a sovereign
              cockpit. By centralizing tasks, CRM, knowledge, and AI into a
              single offline-friendly environment backed by your own data
              (Google Sheets), you eliminate the "app-hopping" tax and achieve
              maximum focus.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              {[
                {
                  label: "Zero Subscription Cost",
                  icon: <Icon.Vault size={12} />,
                },
                { label: "100% Data Ownership", icon: <Icon.Link size={12} /> },
                {
                  label: "AI-Augmented Workflows",
                  icon: <Icon.Bot size={12} />,
                },
              ].map((tag, idx) => (
                <div
                  key={idx}
                  className="flex items-center gap-2 px-3.5 py-2 bg-notion-light-bg dark:bg-notion-dark-bg rounded-xl border border-notion-light-border dark:border-notion-dark-border text-[11px] font-bold text-notion-light-text dark:text-notion-dark-text uppercase tracking-wider hover:bg-notion-light-hover dark:hover:bg-notion-dark-hover transition-colors cursor-default shadow-sm"
                >
                  <span className="opacity-60">{tag.icon}</span>
                  {tag.label}
                </div>
              ))}
            </div>
          </div>
        </div>
        <div className="absolute right-0 bottom-0 opacity-[0.03] dark:opacity-[0.05] p-4 text-notion-light-text dark:text-notion-dark-text group-hover:scale-110 transition-transform duration-1000">
          <Icon.Dashboard size={240} />
        </div>
      </div>
    </div>
  );
};
