import React, { useState } from "react";
import { Icon, iconProps } from "../Icons";
import { BLUEPRINT_MODULES, MODULE_COLORS } from "@/constants";
import { ViewHeader } from "../ViewHeader";
import { toast } from "sonner";
import { Page } from "../../types";
import { Button, Card, Badge } from "../ui";

interface BlueprintViewProps {
  onNavigate?: (page: Page) => void;
  onOpenSettings?: () => void;
}

export const BlueprintView: React.FC<BlueprintViewProps> = React.memo(
  ({ onNavigate, onOpenSettings }) => {
    const [copied, setCopied] = useState(false);
    const crmColors = MODULE_COLORS.crm;
    const docsColors = MODULE_COLORS.docs;

    const copyAsMarkdown = () => {
      const md = [
        "# Master Blueprint - Solo Operator Command Center Roadmap",
        "",
        ...BLUEPRINT_MODULES.map((mod) => {
          return [
            `## ${mod.title} [${mod.status}]`,
            ...mod.features.map((f) => `- ${f}`),
            "",
          ].join("\n");
        }),
        "---",
        "Generated by MyOps - The Master Solo VA App",
      ].join("\n");

      navigator.clipboard.writeText(md).then(() => {
        setCopied(true);
        toast.success("Roadmap copied to clipboard", {
          description: "The full Master Blueprint has been copied as Markdown.",
          icon: <Icon.Copy size={14} />,
        });
        setTimeout(() => setCopied(false), 2000);
      });
    };

    return (
      <div className="space-y-8 animate-in fade-in duration-500">
        <ViewHeader
          title="Master Blueprint"
          subTitle="Solo Operator Command Center Roadmap"
        >
          <div className="flex flex-col sm:flex-row items-center gap-3 w-full sm:w-auto">
            <Button
              onClick={copyAsMarkdown}
              variant="secondary"
              className="w-full sm:w-auto group"
              title="Copy Roadmap as Markdown"
            >
              {copied ? (
                <Icon.Check size={14} className={crmColors.text} />
              ) : (
                <Icon.Copy
                  size={14}
                  className="opacity-60 group-hover:opacity-100"
                />
              )}
              <span className="uppercase tracking-widest text-[10px] font-bold">
                {copied ? "Copied!" : "COPY ROADMAP"}
              </span>
            </Button>

            <div className="w-full sm:w-auto flex items-center justify-center gap-2 px-4 py-2 bg-notion-light-sidebar dark:bg-notion-dark-sidebar rounded-xl border border-notion-light-border dark:border-notion-dark-border">
              <div
                className={`w-1.5 h-1.5 rounded-full ${crmColors.dot} shadow-[0_0_8px_rgba(139,92,246,0.5)] animate-pulse`}
              ></div>
              <span className="text-[10px] font-bold text-notion-light-text dark:text-notion-dark-text opacity-70 uppercase tracking-widest">
                v2.2 Deployment Ready
              </span>
            </div>
          </div>
        </ViewHeader>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {BLUEPRINT_MODULES.map((mod) => {
            const colors = MODULE_COLORS[mod.colorKey] || MODULE_COLORS.tasks;
            return (
              <Card
                key={mod.id}
                className={`relative group h-full flex flex-col ${colors.border.replace("border-", "hover:border-")}`}
                hoverEffect
              >
                <div
                  className={`absolute top-0 right-0 w-32 h-32 ${colors.bg} rounded-full -mr-16 -mt-16 group-hover:scale-150 transition-transform duration-700 opacity-50`}
                ></div>

                <div className="flex items-start justify-between mb-5 relative">
                  <div
                    className={`w-12 h-12 rounded-xl flex items-center justify-center ${colors.lightBg} ${colors.text} border ${colors.border} transition-transform group-hover:scale-110 duration-300`}
                  >
                    {Icon[mod.iconKey as keyof typeof Icon] ? (
                      React.createElement(
                        Icon[mod.iconKey as keyof typeof Icon],
                        {
                          ...iconProps(24),
                        },
                      )
                    ) : (
                      <Icon.Missions {...iconProps(24)} />
                    )}
                  </div>
                  <Badge
                    variant="custom"
                    className={`shadow-sm ${
                      mod.status === "ACTIVE"
                        ? `${crmColors.bg} ${crmColors.text} border ${crmColors.border}`
                        : mod.status === "PARTIAL"
                          ? `${docsColors.bg} ${docsColors.text} border ${docsColors.border}`
                          : "bg-notion-light-sidebar text-notion-light-muted dark:bg-notion-dark-sidebar dark:text-notion-dark-muted border border-notion-light-border dark:border-notion-dark-border"
                    }`}
                  >
                    {mod.status}
                  </Badge>
                </div>

                <h3 className="text-base font-bold text-notion-light-text dark:text-notion-dark-text mb-4 relative group-hover:text-notion-light-text/80 dark:group-hover:text-notion-dark-text/80 transition-colors">
                  {mod.title}
                </h3>

                <ul className="space-y-3 relative flex-grow mb-6">
                  {mod.features.map((f, i) => (
                    <li
                      key={i}
                      className="flex items-start gap-2.5 text-[12px] text-notion-light-muted dark:text-notion-dark-muted group/item"
                    >
                      <div
                        className={`mt-1.5 w-1.5 h-1.5 rounded-full ${colors.dot} opacity-60 group-hover/item:scale-125 transition-transform`}
                      ></div>
                      <span className="leading-tight">{f}</span>
                    </li>
                  ))}
                </ul>

                {mod.links && mod.links.length > 0 && (
                  <div className="relative mb-6 pt-4 border-t border-notion-light-border/50 dark:border-notion-dark-border/30">
                    <div className="flex flex-wrap gap-2">
                      {mod.links.map((link, i) => {
                        const isPlaceholder = link.url === "#";
                        const LinkIcon =
                          link.icon && Icon[link.icon as keyof typeof Icon]
                            ? Icon[link.icon as keyof typeof Icon]
                            : Icon.Link;

                        if (isPlaceholder) {
                          return (
                            <span
                              key={i}
                              className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-notion-light-bg dark:bg-notion-dark-bg border border-notion-light-border dark:border-notion-dark-border text-[10px] font-bold text-notion-light-muted dark:text-notion-dark-muted uppercase tracking-wider cursor-not-allowed opacity-60"
                            >
                              <LinkIcon size={12} />
                              {link.label}
                            </span>
                          );
                        }

                        return (
                          <a
                            key={i}
                            href={link.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-notion-light-bg dark:bg-notion-dark-bg border border-notion-light-border dark:border-notion-dark-border text-[10px] font-bold ${colors.text} uppercase tracking-wider hover:shadow-sm transition-all active:scale-95`}
                          >
                            <LinkIcon size={12} />
                            {link.label}
                          </a>
                        );
                      })}
                    </div>
                  </div>
                )}

                <div className="mt-8 pt-5 border-t border-notion-light-border dark:border-notion-dark-border flex items-center justify-between group-hover:border-notion-light-text/10 dark:group-hover:border-notion-dark-text/10 transition-colors">
                  <Button
                    onClick={() => {
                      if (mod.status === "ACTIVE") {
                        if (mod.pageId === "SETTINGS" && onOpenSettings) {
                          onOpenSettings();
                          return;
                        }

                        if (onNavigate) {
                          const targetPage =
                            mod.pageId || (mod.id.toUpperCase() as Page);
                          onNavigate(targetPage);
                        }
                      } else {
                        toast.info(`${mod.title} initialization`, {
                          description:
                            "This module is in the roadmap and will be available soon.",
                        });
                      }
                    }}
                    variant="custom"
                    size="sm"
                    className={`rounded-lg font-black uppercase tracking-widest ${colors.hoverBg} ${colors.text} group-hover:translate-x-1 ${colors.bg.replace("bg-", "hover:bg-")}`}
                  >
                    {mod.status === "ACTIVE" ? "Open Module" : "Initialize"}{" "}
                    <Icon.Next
                      size={14}
                      className="opacity-0 group-hover:opacity-100 transition-opacity"
                    />
                  </Button>
                </div>
              </Card>
            );
          })}
        </div>

        <Card
          className="bg-notion-light-sidebar dark:bg-notion-dark-sidebar relative group shadow-sm"
          hoverEffect
          padding="lg"
        >
          <div className="absolute top-0 left-0 w-full h-1 bg-notion-light-text dark:bg-notion-dark-text opacity-20 group-hover:opacity-40 transition-opacity"></div>
          <div className="relative z-10 flex flex-col md:flex-row gap-8 items-start">
            <div className="flex-1">
              <h2 className="text-xl font-bold text-notion-light-text dark:text-notion-dark-text mb-4 flex items-center gap-3">
                <Icon.Bot
                  size={24}
                  className="text-notion-light-text dark:text-notion-dark-text opacity-70"
                />
                Operator Philosophy
              </h2>
              <p className="text-notion-light-muted dark:text-notion-dark-muted max-w-2xl leading-relaxed text-[15px]">
                The Master Solo VA App is more than a tool; it's a sovereign
                cockpit. By centralizing tasks, CRM, knowledge, and AI into a
                single offline-friendly environment backed by your own data
                (Google Sheets), you eliminate the "app-hopping" tax and achieve
                maximum focus.
              </p>
              <div className="mt-8 flex flex-wrap gap-3">
                {[
                  {
                    label: "Zero Subscription Cost",
                    icon: <Icon.Vault size={12} />,
                  },
                  {
                    label: "100% Data Ownership",
                    icon: <Icon.Link size={12} />,
                  },
                  {
                    label: "AI-Augmented Workflows",
                    icon: <Icon.Bot size={12} />,
                  },
                ].map((tag, idx) => (
                  <div
                    key={idx}
                    className="flex items-center gap-2 px-3.5 py-2 bg-notion-light-bg dark:bg-notion-dark-bg rounded-xl border border-notion-light-border dark:border-notion-dark-border text-[11px] font-bold text-notion-light-text dark:text-notion-dark-text uppercase tracking-wider hover:bg-notion-light-hover dark:hover:bg-notion-dark-hover transition-colors cursor-default shadow-sm"
                  >
                    <span className="opacity-60">{tag.icon}</span>
                    {tag.label}
                  </div>
                ))}
              </div>
            </div>
          </div>
          <div className="absolute right-0 bottom-0 opacity-[0.03] dark:opacity-[0.05] p-4 text-notion-light-text dark:text-notion-dark-text group-hover:scale-110 transition-transform duration-1000">
            <Icon.Dashboard size={240} />
          </div>
        </Card>
      </div>
    );
  },
);
