
import React from 'react';
import { 
  LayoutDashboard, 
  ClipboardList, 
  Settings, 
  Zap, 
  CheckCircle2, 
  Inbox, 
  AlertCircle, 
  MessageSquareText, 
  Plus, 
  Search, 
  ChevronLeft, 
  ChevronRight, 
  Trash2, 
  Copy, 
  Edit3, 
  Focus, 
  Send, 
  RotateCcw, 
  Play, 
  Pause, 
  X, 
  Bot, 
  ArrowUpRight,
  Menu,
  MoreVertical,
  Check,
  Calendar,
  Layers,
  Link,
  Bold,
  Italic,
  List,
  Code2,
  FileText,
  CopyIcon,
  DuplicateIcon,
  Undo2,
  ChevronDown,
  Monitor
} from 'lucide-react';

export const Icon = {
  Dashboard: LayoutDashboard,
  Missions: ClipboardList,
  Settings: Settings,
  Active: Zap,
  Completed: CheckCircle2,
  Backlog: Inbox,
  Alert: AlertCircle,
  Chat: MessageSquareText,
  Add: Plus,
  Search: Search,
  Prev: ChevronLeft,
  Next: ChevronRight,
  Delete: Trash2,
  Copy: Copy,
  Edit: Edit3,
  Focus: Focus,
  Send: Send,
  Reset: RotateCcw,
  Play: Play,
  Pause: Pause,
  Close: X,
  Bot: Bot,
  External: ArrowUpRight,
  Menu: Menu,
  More: MoreVertical,
  Check: Check,
  Date: Calendar,
  Project: Layers,
  Link: Link,
  Bold: Bold,
  Italic: Italic,
  List: List,
  Code: Code2,
  Template: FileText,
  Undo: Undo2,
  Down: ChevronDown,
  Preview: Monitor
};

// Standard props helper for consistent sizing
export const iconProps = (size = 18, className = "") => ({
  size,
  className,
  strokeWidth: 2
});
