import {
  LayoutDashboard,
  ClipboardList,
  Settings,
  Zap,
  CheckCircle2,
  Inbox,
  AlertCircle,
  MessageSquareText,
  Plus,
  Search,
  ChevronLeft,
  ChevronRight,
  Terminal,
  Trash2,
  Copy,
  Edit3,
  Focus,
  Send,
  RotateCcw,
  Play,
  Pause,
  X,
  Bot,
  ArrowUpRight,
  Menu,
  MoreVertical,
  Check,
  Calendar,
  Layers,
  Link,
  Bold,
  Italic,
  List,
  Code2,
  FileText,
  // Removed CopyIcon and DuplicateIcon (DuplicateIcon does not exist in lucide-react)
  Undo2,
  ChevronDown,
  Monitor,
  Users,
  BookOpen,
  BarChart3,
  Lock,
  Map,
  Moon,
  Sun,
  Tag,
  Book,
  FileCheck,
  Folder,
  Clock,
  Flag,
  Target,
  Activity,
  History,
  Heart,
  Download,
  Database,
  MoreHorizontal,
  MessageSquare,
  Phone,
  Mail,
  Globe,
  ArrowLeft,
  ArrowRight,
} from "lucide-react";

export const Icon = {
  Dashboard: LayoutDashboard,
  Missions: ClipboardList,
  Logo: Terminal,
  Settings: Settings,
  Active: Zap,
  Completed: CheckCircle2,
  Backlog: Inbox,
  Alert: AlertCircle,
  Chat: MessageSquareText,
  Add: Plus,
  Search: Search,
  Prev: ChevronLeft,
  ChevronLeft: ChevronLeft,
  Next: ChevronRight,
  ChevronRight: ChevronRight,
  ArrowRight: ArrowRight,
  Delete: Trash2,
  Copy: Copy,
  Edit: Edit3,
  Focus: Focus,
  Send: Send,
  Reset: RotateCcw,
  Play: Play,
  Pause: Pause,
  Close: X,
  Bot: Bot,
  External: ArrowUpRight,
  Menu: Menu,
  More: MoreVertical,
  Check: Check,
  Date: Calendar,
  Calendar: Calendar,
  Project: Layers,
  Folder: Folder,
  Clock: Clock,
  Flag: Flag,
  ChevronDown: ChevronDown,
  Link: Link,
  Bold: Bold,
  Italic: Italic,
  List: List,
  Code: Code2,
  Template: FileText,
  Download: Download,
  Database: Database,
  Rank: Target,
  Streak: Zap,
  Plus: Plus,
  Notes: BookOpen,
  Contacts: Users,
  Vault: Lock,
  Layout: Map,
  Ai: Bot,
  Undo: Undo2,
  Down: ChevronDown,
  Preview: Monitor,
  Users: Users,
  Docs: BookOpen,
  Analytics: BarChart3,
  Blueprint: Map,
  Zap: Zap,
  Moon: Moon,
  Sun: Sun,
  Tag: Tag,
  Knowledge: Book,
  Report: FileCheck,
  Strategy: Target,
  Target: Target,
  Activity: Activity,
  History: History,
  Heart: Heart,
  MoreHorizontal: MoreHorizontal,
  MessageSquare: MessageSquare,
  Phone: Phone,
  Mail: Mail,
  Globe: Globe,
  ArrowLeft: ArrowLeft,
  X: X,
  Trash: Trash2,
};

// Standard props helper for consistent sizing
export const iconProps = (size = 18, className = "") => ({
  size,
  className,
  strokeWidth: 2,
});
