import { TaskEntry, OperatorMetrics, Contact } from "../types";

export const generateAndDownloadCSV = (entries: TaskEntry[]) => {
  if (entries.length === 0) return false;

  const headers = [
    "ID",
    "Due Date",
    "Task",
    "Project",
    "Priority",
    "Status",
    "Created At",
  ];
  const csvContent = [
    headers.join(","),
    ...entries.map((row) => {
      const escape = (val: string | number | undefined) =>
        `"${String(val ?? "").replace(/"/g, '""')}"`;
      return [
        escape(row.id),
        escape(row.date),
        escape(row.description),
        escape(row.project),
        escape(row.priority),
        escape(row.status),
        escape(row.createdAt),
      ].join(",");
    }),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute(
    "download",
    `myops_export_${new Date().toISOString().split("T")[0]}.csv`,
  );
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  return true;
};

export const generateMarkdownTable = (entries: TaskEntry[]) => {
  if (entries.length === 0) return "";

  const headers = ["Due Date", "Task", "Project", "Priority", "Status"];

  const escapeMarkdown = (text: string | undefined) => {
    if (!text) return "";
    return text.replace(/[|]/g, "\\|");
  };

  const rows = entries.map((row) => [
    row.date || "N/A",
    escapeMarkdown(row.description),
    escapeMarkdown(row.project),
    row.priority,
    row.status,
  ]);

  const headerRow = `| ${headers.join(" | ")} |`;
  const separatorRow = `| ${headers.map(() => "---").join(" | ")} |`;
  const dataRows = rows.map((row) => `| ${row.join(" | ")} |`).join("\n");

  return `${headerRow}\n${separatorRow}\n${dataRows}`;
};

export const generateContactMarkdownTable = (contacts: Contact[]) => {
  if (contacts.length === 0) return "";

  const headers = ["Contact", "Company", "Type", "Status", "Email"];

  const escapeMarkdown = (text: string | undefined) => {
    if (!text) return "";
    return text.replace(/[|]/g, "\\|");
  };

  const rows = contacts.map((contact) => [
    escapeMarkdown(contact.name),
    escapeMarkdown(contact.company),
    contact.type,
    contact.status,
    contact.email || "N/A",
  ]);

  const headerRow = `| ${headers.join(" | ")} |`;
  const separatorRow = `| ${headers.map(() => "---").join(" | ")} |`;
  const dataRows = rows.map((row) => `| ${row.join(" | ")} |`).join("\n");

  return `${headerRow}\n${separatorRow}\n${dataRows}`;
};

interface InsightsExportProps {
  metrics: OperatorMetrics;
  projectData: { name: string; value: number }[];
  activityData: { date: string; created: number; completed: number }[];
  radarData: { subject: string; A: number; fullMark: number }[];
  artifacts: { name: string; condition: string; isUnlocked: boolean }[];
}

export const generateInsightsMarkdown = ({
  metrics,
  projectData,
  activityData,
  radarData,
  artifacts,
}: InsightsExportProps) => {
  const projectSummary = projectData
    .map((p) => `| ${p.name} | ${p.value} |`)
    .join("\n");
  const activitySummary = activityData
    .map((a) => `| ${a.date} | ${a.created} | ${a.completed} |`)
    .join("\n");
  const skillSummary = radarData
    .map((s) => `| ${s.subject} | ${s.A}% |`)
    .join("\n");
  const unlockedArtifacts = artifacts
    .filter((a) => a.isUnlocked)
    .map((a) => `- ${a.name}: ${a.condition}`)
    .join("\n");

  return `
# Operator Insights Report
Generated on: ${new Date().toLocaleString()}

## 📊 Core Metrics
- **Operator Level**: ${metrics.level}
- **Current Rank**: Specialist
- **Total Missions Completed**: ${metrics.totalTasksCompleted}
- **Active Streak**: ${metrics.streak} days
- **Total XP**: ${metrics.xp}

## 🏗️ Project Distribution
| Project | Missions |
| :--- | :--- |
${projectSummary}

## 📈 Weekly Activity
| Day | Created | Completed |
| :--- | :--- | :--- |
${activitySummary}

## ⚡ Operational Skills
| Skill | Level |
| :--- | :--- |
${skillSummary}

## 🏆 Unlocked Artifacts
${unlockedArtifacts || "No artifacts unlocked yet."}

---
Generated by MyOps - The Master Solo VA App
`.trim();
};
